  name: CI
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
      steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: Compile
        run: sbt compile